services:
  app:
    platform: linux/amd64
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 3000:3000
    command: bin/run.bash server
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
