services:
  x86_64: &app
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE

  x86_32: 
    <<: *app
    build: 
      context: .
      dockerfile: Dockerfile.x86_32
